[package]
name = "thimbl"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
cucumber = { version = "0.23.0", features = ["macros", "output-json"] }
gherkin = "0.16.0"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }

[[test]]
name = "cucumber"
harness = false
